### ISSUE TITLE
Drops Symbol fields from the masked object

### ISSUE THREAD

**Issue by aleksandarn** [akozlov75/mask-sensitive-data#10]
Current implementation drops Symbol fields from the masked object. Example:
{
  Symbol(token):"1ab23c.abcabcfff234.fefeffe567e44",
  foo:"message"
}
Expected:
{
  Symbol(token):"1ab*******************44",
  foo:"message"
}
But the result is
{
  foo:"message"
}

Suggestion:
Instead of the stringify and pars implementations used in the library, you can use https://github.com/storybookjs/telejson. This way you can preserve the Symbol properties and reduce the enxternal dependencies.

**Comment by akozlov75** [comment]
Nice, will add this possibility in PR #12
